  {
    id: 'af-009', cuisine: 'africaine', name: 'Ndolé Camerounais',
    type: 'dîner', difficulty: 'Moyen', prepTime: '30 min', cookTime: '60 min',
    servings: 4, kcalPerPerson: 520, proteinPerPerson: 32, carbsPerPerson: 22,
    diets: [], imageQuery: 'ndole cameroon stew bitter leaves peanuts',
    ingredients: [
      { quantity: '400', unit: 'g',   name: 'feuilles de ndolé (ou épinards amers)' },
      { quantity: '300', unit: 'g',   name: 'bœuf coupé en dés' },
      { quantity: '200', unit: 'g',   name: 'crevettes décortiquées' },
      { quantity: '150', unit: 'g',   name: 'arachides grillées moulues' },
      { quantity: '2',   unit: '',    name: 'oignons émincés' },
      { quantity: '4',   unit: '',    name: 'gousses d\'ail écrasées' },
      { quantity: '3',   unit: 'c.s', name: 'huile de palme' },
      { quantity: '1',   unit: 'c.c', name: 'poivre noir moulu' },
    ],
    steps: [
      'Blanchir les feuilles de ndolé dans de l\'eau bouillante salée pendant 5 minutes pour réduire l\'amertume, puis les égoutter et les presser pour en extraire l\'eau.',
      'Dans une grande casserole, chauffer l\'huile de palme à feu moyen. Faire revenir les oignons et l\'ail jusqu\'à dorure, environ 5 minutes.',
      'Ajouter le bœuf et faire sauter jusqu\'à ce qu\'il soit bien coloré de toutes parts, environ 8 minutes. Incorporer les arachides moulues et bien mélanger.',
      'Ajouter les feuilles de ndolé égouttées, mélanger pour bien enrober le tout d\'arachides. Verser 20 cl d\'eau, couvrir et laisser mijoter 30 minutes à feu doux.',
      'Incorporer les crevettes 10 minutes avant la fin de la cuisson. Rectifier l\'assaisonnement en sel et poivre. Servir chaud avec du riz blanc ou des plantains bouillis.',
    ],
    chefTip: 'Les arachides moulues doivent être torréfiées à sec avant d\'être broyées pour développer leur saveur. Si vous utilisez des épinards à la place du ndolé, ajoutez une touche de jus de citron pour simuler l\'amertume caractéristique.',
    childNote: 'Peut être préparé moins épicé en retirant le poivre — les enfants apprécient généralement la sauce aux arachides.',
  },
  {
    id: 'af-010', cuisine: 'africaine', name: 'Egusi Soup Nigériane',
    type: 'dîner', difficulty: 'Moyen', prepTime: '25 min', cookTime: '50 min',
    servings: 4, kcalPerPerson: 490, proteinPerPerson: 29, carbsPerPerson: 18,
    diets: [], imageQuery: 'egusi soup nigeria melon seed stew spinach',
    ingredients: [
      { quantity: '200', unit: 'g',   name: 'graines d\'egusi (courge) moulues' },
      { quantity: '400', unit: 'g',   name: 'poulet coupé en morceaux' },
      { quantity: '150', unit: 'g',   name: 'feuilles d\'ugu (ou épinards)' },
      { quantity: '3',   unit: 'c.s', name: 'huile de palme' },
      { quantity: '2',   unit: '',    name: 'tomates fraîches mixées' },
      { quantity: '1',   unit: '',    name: 'oignon moyen mixé' },
      { quantity: '2',   unit: '',    name: 'piments rouges (ajuster au goût)' },
      { quantity: '1',   unit: 'c.c', name: 'poudre de crayfish (crevettes séchées)' },
    ],
    steps: [
      'Assaisonner le poulet de sel, poivre et d\'un cube de bouillon. Le faire cuire à l\'eau pendant 20 minutes jusqu\'à ce qu\'il soit tendre. Réserver le bouillon de cuisson.',
      'Mélanger les graines d\'egusi moulues avec un peu d\'eau pour former une pâte épaisse. Faire chauffer l\'huile de palme dans une grande casserole à feu moyen.',
      'Faire revenir les tomates, l\'oignon et les piments mixés dans l\'huile de palme pendant 10 minutes jusqu\'à évaporation de l\'eau des tomates.',
      'Ajouter la pâte d\'egusi par petites cuillerées dans la sauce tomate sans mélanger immédiatement — laisser former de petits grumeaux qui vont cuire dans la sauce, environ 10 minutes.',
      'Incorporer le poulet, la poudre de crayfish et 25 cl de bouillon de cuisson. Laisser mijoter 15 minutes. Ajouter les feuilles d\'ugu, mélanger et cuire encore 5 minutes. Servir avec du fufu ou de l\'eba.',
    ],
    chefTip: 'Le secret de l\'Egusi Soup réside dans la technique de cuisson de la pâte d\'egusi : ne pas mélanger immédiatement après l\'ajout permet de former des petits grumeaux fermes appelés "egusi lumps" qui apportent une texture unique au plat.',
    childNote: null,
  },
  {
    id: 'af-011', cuisine: 'africaine', name: 'Poulet Yassa Sénégalais',
    type: 'dîner', difficulty: 'Facile', prepTime: '20 min', cookTime: '45 min',
    servings: 4, kcalPerPerson: 410, proteinPerPerson: 38, carbsPerPerson: 15,
    diets: ['sans-gluten'], imageQuery: 'yassa poulet senegal onion lemon chicken',
    ingredients: [
      { quantity: '1',   unit: 'kg',  name: 'poulet découpé en morceaux' },
      { quantity: '4',   unit: '',    name: 'gros oignons émincés en lamelles' },
      { quantity: '3',   unit: '',    name: 'citrons (jus)' },
      { quantity: '4',   unit: 'c.s', name: 'moutarde de Dijon' },
      { quantity: '2',   unit: '',    name: 'piments verts entiers' },
      { quantity: '4',   unit: '',    name: 'gousses d\'ail écrasées' },
      { quantity: '3',   unit: 'c.s', name: 'huile végétale' },
      { quantity: '1',   unit: 'c.c', name: 'poivre noir moulu' },
    ],
    steps: [
      'Préparer la marinade en mélangeant le jus des citrons, la moutarde, l\'ail, le sel et le poivre. Ajouter les oignons et les morceaux de poulet, bien mélanger et laisser mariner au minimum 2 heures (idéalement une nuit).',
      'Retirer le poulet de la marinade, réserver les oignons et la marinade séparément. Faire griller ou saisir le poulet à la poêle avec un filet d\'huile jusqu\'à belle coloration.',
      'Dans la même poêle ou une casserole, faire revenir les oignons marinés à feu moyen pendant 15 minutes jusqu\'à ce qu\'ils deviennent dorés et fondants.',
      'Verser la marinade réservée dans la casserole, ajouter les piments entiers et un peu d\'eau si nécessaire. Porter à ébullition puis réduire le feu.',
      'Remettre le poulet grillé dans la sauce aux oignons. Couvrir et laisser mijoter 25 minutes à feu doux. Retirer les piments avant de servir avec du riz blanc.',
    ],
    chefTip: 'Griller le poulet avant de le mijoter est l\'étape clé du Yassa : la réaction de Maillard crée une croûte dorée qui apporte de la profondeur à la sauce. La marinade longue (une nuit) attendrit considérablement la viande.',
    childNote: 'Retirer les piments entiers avant de servir aux enfants — le plat reste savoureux sans être piquant.',
  },
  {
    id: 'af-012', cuisine: 'africaine', name: 'Shakshuka Tunisien',
    type: 'déjeuner', difficulty: 'Facile', prepTime: '10 min', cookTime: '25 min',
    servings: 4, kcalPerPerson: 280, proteinPerPerson: 16, carbsPerPerson: 20,
    diets: ['végétarien', 'sans-gluten'], imageQuery: 'shakshuka eggs tomato sauce harissa tunisia',
    ingredients: [
      { quantity: '6',   unit: '',    name: 'œufs frais' },
      { quantity: '4',   unit: '',    name: 'tomates mûres concassées' },
      { quantity: '2',   unit: '',    name: 'poivrons rouges coupés en dés' },
      { quantity: '1',   unit: '',    name: 'oignon moyen émincé' },
      { quantity: '2',   unit: 'c.s', name: 'harissa tunisienne' },
      { quantity: '3',   unit: '',    name: 'gousses d\'ail écrasées' },
      { quantity: '2',   unit: 'c.s', name: 'huile d\'olive' },
      { quantity: '1',   unit: 'c.c', name: 'cumin en poudre' },
    ],
    steps: [
      'Chauffer l\'huile d\'olive dans une grande poêle à bords hauts. Faire revenir l\'oignon et les poivrons à feu moyen pendant 8 minutes jusqu\'à ramollissement.',
      'Ajouter l\'ail, le cumin et la harissa. Faire revenir encore 2 minutes en remuant pour libérer les arômes des épices.',
      'Incorporer les tomates concassées avec leur jus, saler et poivrer. Laisser mijoter à découvert 10 minutes pour que la sauce épaississe.',
      'Avec le dos d\'une cuillère, former 6 petits creux dans la sauce. Casser délicatement un œuf dans chaque creux sans crever le jaune.',
      'Couvrir la poêle et cuire 5 à 7 minutes selon la cuisson désirée (jaune coulant ou cuit). Garnir de persil frais haché et servir directement dans la poêle avec du pain croustillant.',
    ],
    chefTip: 'La clé d\'un shakshuka réussi est de cuire les œufs à la vapeur en couvrant la poêle plutôt qu\'en les retournant. Pour des blancs parfaitement cuits et un jaune encore coulant, comptez exactement 5 minutes après avoir posé le couvercle.',
    childNote: 'Réduire la harissa à 1 c.c ou la remplacer par du concentré de tomate pour les enfants sensibles au piment.',
  },
  {
    id: 'af-013', cuisine: 'africaine', name: 'Ful Medames Égyptien',
    type: 'petit-déjeuner', difficulty: 'Facile', prepTime: '10 min', cookTime: '20 min',
    servings: 4, kcalPerPerson: 310, proteinPerPerson: 18, carbsPerPerson: 42,
    diets: ['vegan', 'sans-gluten'], imageQuery: 'ful medames egyptian fava beans breakfast lemon',
    ingredients: [
      { quantity: '500', unit: 'g',   name: 'fèves cuites (en conserve, égouttées)' },
      { quantity: '3',   unit: 'c.s', name: 'huile d\'olive extra vierge' },
      { quantity: '2',   unit: '',    name: 'citrons (jus)' },
      { quantity: '3',   unit: '',    name: 'gousses d\'ail écrasées' },
      { quantity: '1',   unit: 'c.c', name: 'cumin en poudre' },
      { quantity: '1',   unit: 'pincée', name: 'piment de Cayenne' },
      { quantity: '1',   unit: '',    name: 'bouquet de persil plat haché' },
      { quantity: '4',   unit: '',    name: 'œufs durs (optionnel, pour servir)' },
    ],
    steps: [
      'Égoutter et rincer les fèves. Les placer dans une casserole avec 10 cl d\'eau et chauffer à feu moyen jusqu\'à ce qu\'elles soient bien chaudes, environ 5 minutes.',
      'Écraser grossièrement la moitié des fèves avec le dos d\'une fourchette pour obtenir une texture mi-lisse, mi-entière. C\'est la texture traditionnelle du ful medames.',
      'Retirer du feu, assaisonner généreusement avec l\'ail écrasé, le jus de citron, le cumin et la pincée de piment. Bien mélanger.',
      'Verser dans des bols de service. Arroser généreusement d\'huile d\'olive et parsemer de persil frais haché.',
      'Servir chaud accompagné d\'œufs durs coupés en quartiers, de pain pita chaud et de légumes frais (tomates, concombres). Proposer des quartiers de citron supplémentaires à table.',
    ],
    chefTip: 'L\'huile d\'olive versée crue en finition est indispensable : elle apporte une richesse fruitée que la cuisson détruirait. Utilisez une huile de qualité au goût prononcé. L\'ail cru ajouté hors feu conserve toute sa puissance aromatique.',
    childNote: 'Omettre le piment et réduire l\'ail — les fèves écrasées avec huile d\'olive et citron sont douces et très appréciées des enfants.',
  },
  {
    id: 'af-014', cuisine: 'africaine', name: 'Kelewele — Plantains Épicés Frits',
    type: 'collation', difficulty: 'Facile', prepTime: '15 min', cookTime: '15 min',
    servings: 4, kcalPerPerson: 290, proteinPerPerson: 3, carbsPerPerson: 52,
    diets: ['vegan', 'sans-gluten'], imageQuery: 'kelewele ghana fried plantain spiced street food',
    ingredients: [
      { quantity: '3',   unit: '',    name: 'bananes plantains bien mûres (à peau noire)' },
      { quantity: '1',   unit: 'c.c', name: 'gingembre frais râpé' },
      { quantity: '1',   unit: 'c.c', name: 'piment de Cayenne moulu' },
      { quantity: '1',   unit: 'c.c', name: 'poudre d\'oignon' },
      { quantity: '1',   unit: 'pincée', name: 'sel' },
      { quantity: '1',   unit: 'c.c', name: 'poudre de noix de muscade' },
      { quantity: '50',  unit: 'cl',  name: 'huile végétale pour friture' },
    ],
    steps: [
      'Éplucher les plantains et les couper en cubes d\'environ 2 cm ou en rondelles épaisses en biais. Plus le plantain est mûr (peau noire), plus il sera sucré et fondant.',
      'Dans un grand bol, mélanger le gingembre, le piment, la poudre d\'oignon, la muscade et le sel. Ajouter les morceaux de plantain et bien enrober de ce mélange d\'épices.',
      'Laisser mariner 10 minutes pour que les épices pénètrent les plantains.',
      'Chauffer l\'huile à 180 °C dans une poêle profonde. Frire les plantains épicés par petites quantités, 3-4 minutes de chaque côté, jusqu\'à ce qu\'ils soient bien dorés et légèrement caramélisés.',
      'Égoutter sur du papier absorbant. Servir immédiatement bien chaud comme en-cas ou en accompagnement d\'un plat principal.',
    ],
    chefTip: 'La maturité du plantain est le facteur déterminant : un plantain à peau jaune donnera un résultat ferme et peu sucré, tandis qu\'un plantain à peau noire sera fondant et naturellement caramélisé. Attendez toujours la peau noire pour le kelewele.',
    childNote: 'Réduire le piment à une simple pincée ou l\'omettre — les plantains mûrs frits sont naturellement sucrés et adorés des enfants.',
  },
  {
    id: 'af-015', cuisine: 'africaine', name: 'Couscous Algérien aux Légumes',
    type: 'dîner', difficulty: 'Moyen', prepTime: '30 min', cookTime: '60 min',
    servings: 6, kcalPerPerson: 480, proteinPerPerson: 22, carbsPerPerson: 65,
    diets: ['végétarien'], imageQuery: 'algerian couscous vegetables chickpeas harissa',
    ingredients: [
      { quantity: '500', unit: 'g',   name: 'couscous moyen' },
      { quantity: '2',   unit: '',    name: 'courgettes coupées en rondelles épaisses' },
      { quantity: '2',   unit: '',    name: 'carottes coupées en tronçons' },
      { quantity: '1',   unit: '',    name: 'navet coupé en quartiers' },
      { quantity: '200', unit: 'g',   name: 'pois chiches cuits (en conserve)' },
      { quantity: '2',   unit: '',    name: 'tomates concassées' },
      { quantity: '1',   unit: 'c.s', name: 'ras-el-hanout' },
      { quantity: '3',   unit: 'c.s', name: 'huile d\'olive' },
    ],
    steps: [
      'Dans une grande casserole, faire revenir un oignon émincé dans l\'huile d\'olive. Ajouter le ras-el-hanout et les tomates concassées, cuire 5 minutes.',
      'Ajouter les carottes et les navets (les légumes les plus durs), couvrir d\'eau, saler et porter à ébullition. Cuire 15 minutes.',
      'Ajouter les courgettes et les pois chiches. Poursuivre la cuisson 15 minutes. Le bouillon doit être savoureux et légèrement coloré.',
      'Préparer le couscous : verser le couscous dans un grand saladier, arroser de 50 cl de bouillon chaud prélevé sur les légumes, couvrir d\'un film et laisser gonfler 5 minutes.',
      'Égrainer le couscous à la fourchette avec une noix de beurre ou un filet d\'huile d\'olive. Dresser dans un grand plat creux : couscous en dôme au centre, légumes et bouillon autour. Servir avec de la harissa diluée en sauce à part.',
    ],
    chefTip: 'Le secret du couscous parfait est de le gonfler avec le bouillon de cuisson des légumes plutôt qu\'avec de l\'eau : il absorbe ainsi toute la profondeur aromatique du plat. Égrainer trois fois durant le gonflement pour éviter les grumeaux.',
    childNote: 'Servir le bouillon et les légumes sans harissa pour les enfants — le couscous nature avec du beurre est très apprécié.',
  },
  {
    id: 'af-016', cuisine: 'africaine', name: 'Chapati Kenyan',
    type: 'déjeuner', difficulty: 'Facile', prepTime: '20 min', cookTime: '20 min',
    servings: 4, kcalPerPerson: 320, proteinPerPerson: 8, carbsPerPerson: 55,
    diets: ['végétarien'], imageQuery: 'kenyan chapati flatbread layered flaky',
    ingredients: [
      { quantity: '400', unit: 'g',   name: 'farine de blé tout usage' },
      { quantity: '1',   unit: 'c.c', name: 'sel fin' },
      { quantity: '1',   unit: 'c.s', name: 'sucre en poudre' },
      { quantity: '20',  unit: 'cl',  name: 'eau tiède' },
      { quantity: '4',   unit: 'c.s', name: 'huile végétale (+ pour la cuisson)' },
    ],
    steps: [
      'Dans un grand bol, mélanger la farine, le sel et le sucre. Former un puits, ajouter 2 c.s d\'huile et l\'eau tiède progressivement en pétrissant jusqu\'à obtenir une pâte souple et non collante. Pétrir 8 minutes.',
      'Couvrir d\'un linge humide et laisser reposer 15 minutes. Diviser la pâte en 8 boules égales.',
      'Étaler chaque boule en un disque fin. Badigeonner d\'un peu d\'huile, rouler en boudin, puis enrouler le boudin en spirale (comme un escargot). Aplatir à nouveau ce "escargot" en un disque de 20 cm — cette technique crée les couches feuilletées.',
      'Chauffer une poêle à sec à feu moyen-vif. Cuire chaque chapati 2 minutes jusqu\'à l\'apparition de taches dorées, retourner, huiler légèrement les bords et cuire encore 2 minutes.',
      'Envelopper les chapatis cuits dans un linge propre pour les garder souples. Servir chauds avec du curry, des haricots ou un ragoût.',
    ],
    chefTip: 'La technique de l\'enroulement en spirale avant d\'aplatir à nouveau est le secret du chapati kenyan feuilleté : elle crée des couches de pâte séparées par l\'huile qui se délitent à la cuisson. Ne sautez pas cette étape.',
    childNote: 'Les enfants adorent manger le chapati en le déchirant avec leurs doigts — servir avec du miel ou de la confiture pour le petit-déjeuner.',
  },
  {
    id: 'af-017', cuisine: 'africaine', name: 'Pilau Kenyan',
    type: 'dîner', difficulty: 'Moyen', prepTime: '20 min', cookTime: '50 min',
    servings: 4, kcalPerPerson: 530, proteinPerPerson: 33, carbsPerPerson: 58,
    diets: ['sans-gluten'], imageQuery: 'kenyan pilau rice spiced meat cumin cardamom',
    ingredients: [
      { quantity: '400', unit: 'g',   name: 'riz basmati rincé' },
      { quantity: '500', unit: 'g',   name: 'bœuf coupé en dés' },
      { quantity: '2',   unit: '',    name: 'oignons finement émincés' },
      { quantity: '1',   unit: 'c.c', name: 'graines de cumin' },
      { quantity: '6',   unit: '',    name: 'gousses de cardamome entières' },
      { quantity: '1',   unit: 'c.c', name: 'poivre noir en grains' },
      { quantity: '2',   unit: '',    name: 'bâtons de cannelle' },
      { quantity: '3',   unit: 'c.s', name: 'huile végétale' },
    ],
    steps: [
      'Faire chauffer l\'huile dans une grande casserole à fond épais. Faire revenir les oignons à feu moyen jusqu\'à ce qu\'ils soient bien dorés, presque caramélisés, environ 15 minutes — c\'est la base aromatique du pilau.',
      'Ajouter les graines de cumin, la cardamome, le poivre en grains et la cannelle. Faire sauter 1 minute pour torréfier les épices entières dans l\'huile chaude.',
      'Ajouter les dés de bœuf, saler et faire sauter à feu vif jusqu\'à coloration complète, environ 8 minutes. Ajouter 2 gousses d\'ail et du gingembre râpé (optionnel).',
      'Verser 80 cl d\'eau, porter à ébullition, puis réduire le feu. Laisser cuire le bœuf à couvert pendant 20 minutes jusqu\'à tendreté.',
      'Ajouter le riz rincé directement dans le bouillon. Mélanger une fois, couvrir hermétiquement et cuire à feu très doux 18 minutes sans soulever le couvercle. Laisser reposer 5 minutes avant de servir.',
    ],
    chefTip: 'La caramélisation profonde des oignons est essentielle : ils doivent être presque brûlés en apparence mais pas amers. Ces oignons ultra-dorés donnent au pilau sa couleur brun dorée caractéristique et sa saveur complexe. Prenez le temps nécessaire pour cette étape.',
    childNote: null,
  },
  {
    id: 'af-018', cuisine: 'africaine', name: 'Sambuusa Somalien',
    type: 'collation', difficulty: 'Moyen', prepTime: '40 min', cookTime: '20 min',
    servings: 4, kcalPerPerson: 380, proteinPerPerson: 18, carbsPerPerson: 34,
    diets: [], imageQuery: 'somali sambuusa samosa fried pastry meat filling',
    ingredients: [
      { quantity: '300', unit: 'g',   name: 'farine de blé' },
      { quantity: '250', unit: 'g',   name: 'viande hachée de bœuf ou d\'agneau' },
      { quantity: '1',   unit: '',    name: 'oignon finement haché' },
      { quantity: '1',   unit: 'c.c', name: 'poudre de cumin' },
      { quantity: '1',   unit: 'c.c', name: 'poudre de coriandre' },
      { quantity: '2',   unit: '',    name: 'piments verts hachés fins' },
      { quantity: '1',   unit: '',    name: 'bouquet de coriandre fraîche hachée' },
      { quantity: '50',  unit: 'cl',  name: 'huile végétale pour friture' },
    ],
    steps: [
      'Préparer la pâte : mélanger la farine, une pincée de sel et 3 c.s d\'huile. Ajouter de l\'eau tiède progressivement pour former une pâte ferme. Pétrir 5 minutes, couvrir et laisser reposer 20 minutes.',
      'Préparer la farce : faire revenir l\'oignon dans une poêle avec un filet d\'huile. Ajouter la viande hachée, émietter à la spatule et cuire jusqu\'à complète absorption de l\'eau, environ 8 minutes.',
      'Assaisonner la farce avec le cumin, la coriandre, les piments, le sel et la coriandre fraîche. Laisser refroidir complètement.',
      'Étaler la pâte finement et découper en rectangles de 10x15 cm. Plier chaque rectangle en triangle en créant une poche, la remplir de farce et sceller les bords avec une pâte d\'eau et farine.',
      'Frire les sambuusas dans l\'huile chaude à 175 °C pendant 3-4 minutes de chaque côté jusqu\'à dorure. Égoutter sur papier absorbant. Servir chaud avec du chutney de coriandre.',
    ],
    chefTip: 'La pâte doit être suffisamment ferme pour ne pas absorber l\'huile à la friture. La farce doit être parfaitement sèche et refroidie avant le pliage, sinon elle ramollit la pâte de l\'intérieur et les sambuusas éclatent à la friture.',
    childNote: 'Omettre les piments verts dans la farce pour les enfants — la farce épicée au cumin reste délicieuse et accessible.',
  },
  {
    id: 'af-019', cuisine: 'africaine', name: 'Maharagwe — Haricots Rouges Kényans',
    type: 'déjeuner', difficulty: 'Facile', prepTime: '10 min', cookTime: '30 min',
    servings: 4, kcalPerPerson: 350, proteinPerPerson: 16, carbsPerPerson: 48,
    diets: ['vegan', 'sans-gluten'], imageQuery: 'maharagwe kenyan red kidney beans coconut milk stew',
    ingredients: [
      { quantity: '400', unit: 'g',   name: 'haricots rouges cuits (en conserve)' },
      { quantity: '20',  unit: 'cl',  name: 'lait de coco' },
      { quantity: '2',   unit: '',    name: 'tomates fraîches hachées' },
      { quantity: '1',   unit: '',    name: 'oignon moyen haché' },
      { quantity: '2',   unit: '',    name: 'gousses d\'ail émincées' },
      { quantity: '1',   unit: 'c.c', name: 'curcuma en poudre' },
      { quantity: '1',   unit: 'c.c', name: 'cumin en poudre' },
      { quantity: '2',   unit: 'c.s', name: 'huile végétale' },
    ],
    steps: [
      'Chauffer l\'huile dans une casserole à feu moyen. Faire revenir l\'oignon jusqu\'à transparence, puis ajouter l\'ail et cuire encore 2 minutes.',
      'Ajouter les tomates hachées, le curcuma et le cumin. Faire mijoter 8 minutes en remuant souvent jusqu\'à ce que les tomates se défassent et forment une sauce.',
      'Incorporer les haricots rouges égouttés et le lait de coco. Bien mélanger, saler selon le goût.',
      'Laisser mijoter à feu doux 15 minutes à découvert pour que la sauce épaississe et que les saveurs se mêlent. Écraser quelques haricots contre le bord pour lier davantage la sauce.',
      'Rectifier l\'assaisonnement. Servir chaud sur du riz blanc ou avec du chapati. Garnir de coriandre fraîche si disponible.',
    ],
    chefTip: 'Le lait de coco doit être ajouté après les épices et les tomates, jamais avant : une chaleur trop vive au début fait granuler les protéines du lait de coco. Écraser quelques haricots en fin de cuisson épaissit naturellement la sauce sans ajout de fécule.',
    childNote: 'Plat naturellement doux et très apprécié des enfants — servir avec du riz et une noix de beurre pour les plus petits.',
  },
  {
    id: 'af-020', cuisine: 'africaine', name: 'Poulet Piri-Piri Mozambicain',
    type: 'dîner', difficulty: 'Moyen', prepTime: '20 min', cookTime: '45 min',
    servings: 4, kcalPerPerson: 440, proteinPerPerson: 42, carbsPerPerson: 8,
    diets: ['sans-gluten'], imageQuery: 'mozambique piri piri grilled chicken chili sauce',
    ingredients: [
      { quantity: '1',   unit: 'kg',  name: 'poulet coupé en morceaux ou en crapaudine' },
      { quantity: '6',   unit: '',    name: 'piments piri-piri (ou piments rouges forts)' },
      { quantity: '4',   unit: '',    name: 'gousses d\'ail' },
      { quantity: '3',   unit: 'c.s', name: 'huile d\'olive' },
      { quantity: '2',   unit: '',    name: 'citrons (jus)' },
      { quantity: '1',   unit: 'c.c', name: 'paprika fumé' },
      { quantity: '1',   unit: 'c.c', name: 'origan séché' },
      { quantity: '1',   unit: 'c.c', name: 'sel' },
    ],
    steps: [
      'Préparer la sauce piri-piri : mixer les piments, l\'ail, l\'huile d\'olive, le jus de citron, le paprika, l\'origan et le sel jusqu\'à obtenir une sauce lisse et homogène.',
      'Inciser profondément la chair du poulet avec un couteau pour permettre à la marinade de pénétrer. Enrober généreusement tous les morceaux de sauce piri-piri.',
      'Laisser mariner au réfrigérateur minimum 2 heures, idéalement une nuit. Sortir le poulet 30 minutes avant cuisson pour le ramener à température ambiante.',
      'Cuire au four préchauffé à 200 °C pendant 40 minutes, en arrosant de sauce toutes les 10 minutes. Activer le grill les 5 dernières minutes pour une belle peau croustillante.',
      'Laisser reposer 5 minutes avant de servir. Accompagner de légumes grillés, de riz ou de pain de maïs. Servir avec des quartiers de citron.',
    ],
    chefTip: 'Les incisions dans la chair sont essentielles pour un poulet piri-piri authentique : la marinade doit atteindre l\'os pour une saveur profonde. Arroser régulièrement durant la cuisson empêche le dessèchement et crée une laque brillante caractéristique.',
    childNote: 'Réserver une portion de poulet avant l\'ajout de la sauce piri-piri, assaisonner simplement avec huile d\'olive, citron et origan pour les enfants.',
  },
  {
    id: 'af-021', cuisine: 'africaine', name: 'Fufu et Soupe d\'Arachide',
    type: 'dîner', difficulty: 'Moyen', prepTime: '20 min', cookTime: '40 min',
    servings: 4, kcalPerPerson: 610, proteinPerPerson: 28, carbsPerPerson: 72,
    diets: [], imageQuery: 'fufu groundnut peanut soup west africa ghana',
    ingredients: [
      { quantity: '600', unit: 'g',   name: 'igname ou plantain (pour le fufu)' },
      { quantity: '200', unit: 'g',   name: 'pâte d\'arachide (beurre de cacahuète sans sucre)' },
      { quantity: '400', unit: 'g',   name: 'poulet coupé en morceaux' },
      { quantity: '2',   unit: '',    name: 'tomates mixées' },
      { quantity: '1',   unit: '',    name: 'oignon mixé' },
      { quantity: '2',   unit: '',    name: 'piments rouges' },
      { quantity: '1',   unit: 'L',   name: 'bouillon de poulet' },
      { quantity: '2',   unit: 'c.s', name: 'huile végétale' },
    ],
    steps: [
      'Préparer le fufu : éplucher et couper l\'igname en morceaux, faire bouillir 20 minutes jusqu\'à tendreté complète. Égoutter et piler énergiquement dans un mortier jusqu\'à obtenir une masse lisse, élastique et sans grumeaux. Former en boules.',
      'Pour la soupe : faire revenir l\'oignon et les tomates dans l\'huile chaude 5 minutes. Ajouter le poulet et le saisir de toutes parts.',
      'Délayer la pâte d\'arachide dans 25 cl de bouillon chaud jusqu\'à consistance homogène. Verser ce mélange dans la casserole avec le reste du bouillon.',
      'Ajouter les piments entiers, couvrir et laisser mijoter 25 minutes à feu doux en remuant souvent pour éviter que la soupe n\'attache au fond.',
      'Retirer les piments, rectifier l\'assaisonnement en sel. La soupe doit napper légèrement la cuillère. Servir les boules de fufu dans des assiettes creuses, napper de soupe d\'arachide généreusement.',
    ],
    chefTip: 'La consistance du fufu est cruciale : il doit être assez ferme pour être saisi avec les doigts, formé en petite boule et utilisé pour ramasser la soupe. Si trop collant, continuer à piler ; si trop dur, ajouter quelques gouttes d\'eau chaude. La pâte d\'arachide doit être diluée à part avant d\'être ajoutée pour éviter les grumeaux.',
    childNote: 'Le fufu peut être remplacé par du riz blanc pour les enfants peu habitués à cette texture — la soupe d\'arachide douce est souvent un succès.',
  },
  {
    id: 'af-022', cuisine: 'africaine', name: 'Ceebu Yapp — Riz à la Viande Sénégalais',
    type: 'dîner', difficulty: 'Difficile', prepTime: '30 min', cookTime: '70 min',
    servings: 6, kcalPerPerson: 560, proteinPerPerson: 35, carbsPerPerson: 62,
    diets: ['sans-gluten'], imageQuery: 'ceebu yapp senegal rice meat tomato west africa',
    ingredients: [
      { quantity: '600', unit: 'g',   name: 'riz blanc à grains courts' },
      { quantity: '700', unit: 'g',   name: 'bœuf ou agneau coupé en gros morceaux' },
      { quantity: '4',   unit: 'c.s', name: 'concentré de tomate' },
      { quantity: '3',   unit: '',    name: 'tomates fraîches mixées' },
      { quantity: '2',   unit: '',    name: 'oignons émincés' },
      { quantity: '4',   unit: '',    name: 'gousses d\'ail écrasées' },
      { quantity: '3',   unit: 'c.s', name: 'huile de palme ou végétale' },
      { quantity: '1',   unit: 'c.s', name: 'poudre de yeet (poisson fermenté) ou pâte de crevettes' },
    ],
    steps: [
      'Préparer le rof : mixer l\'ail avec du persil et du poivre pour obtenir une pâte. Inciser la viande et farcir les incisions de cette pâte aromatique. Laisser reposer 15 minutes.',
      'Chauffer l\'huile dans une grande cocotte, faire dorer la viande sur toutes les faces à feu vif. Retirer et réserver. Dans la même huile, faire revenir les oignons jusqu\'à dorure.',
      'Ajouter le concentré de tomate et les tomates fraîches mixées. Cuire en remuant à feu moyen pendant 15 minutes jusqu\'à obtenir une sauce foncée et épaisse (la sauce doit perdre toute son acidité).',
      'Remettre la viande, ajouter la poudre de yeet, couvrir d\'eau et laisser mijoter 30 minutes. Goûter et rectifier en sel. Prélever 1,2 L de ce bouillon rouge pour cuire le riz.',
      'Porter le bouillon à ébullition, ajouter le riz rincé, couvrir hermétiquement et cuire à feu très doux 20 minutes. Laisser reposer 10 minutes avant d\'ouvrir. Dresser : riz au centre, viande et sauce autour.',
    ],
    chefTip: 'La sauce tomate doit cuire jusqu\'à ce qu\'elle "tourne" — elle fonce, se concentre et perd son acidité. C\'est l\'étape la plus importante : une sauce insuffisamment cuite donne un plat acide et peu profond. Comptez au moins 15 minutes de cuisson de la sauce avant d\'ajouter la viande.',
    childNote: 'Réserver quelques morceaux de viande sans les épices du rof pour les tout-petits — le riz cuit dans le bouillon de viande est naturellement savoureux.',
  },
  {
    id: 'af-023', cuisine: 'africaine', name: 'Biltong Sud-Africain',
    type: 'collation', difficulty: 'Difficile', prepTime: '30 min', cookTime: '0 min',
    servings: 8, kcalPerPerson: 180, proteinPerPerson: 30, carbsPerPerson: 2,
    diets: ['sans-gluten'], imageQuery: 'south african biltong dried cured beef spices',
    ingredients: [
      { quantity: '1',   unit: 'kg',  name: 'bœuf tende de tranche coupé en lanières de 2 cm' },
      { quantity: '3',   unit: 'c.s', name: 'vinaigre de cidre' },
      { quantity: '2',   unit: 'c.s', name: 'gros sel' },
      { quantity: '1',   unit: 'c.s', name: 'sucre brun' },
      { quantity: '2',   unit: 'c.s', name: 'graines de coriandre grossièrement moulues' },
      { quantity: '1',   unit: 'c.c', name: 'poivre noir moulu' },
      { quantity: '1',   unit: 'c.c', name: 'paprika' },
    ],
    steps: [
      'Tremper les lanières de bœuf dans le vinaigre de cidre pendant 30 minutes. Ce bain acide attendrit la viande et agit comme agent de conservation naturel.',
      'Mélanger le sel, le sucre brun, la coriandre moulue, le poivre et le paprika dans un bol. Retirer la viande du vinaigre, égoutter sans rincer, puis frotter généreusement de ce mélange d\'épices.',
      'Placer les lanières sur une grille (ou les suspendre avec des crochets) dans un endroit sec et bien ventilé, ou dans un déshydrateur alimentaire à 40 °C.',
      'Laisser sécher 3 à 5 jours selon l\'épaisseur des lanières et l\'humidité ambiante. Le biltong est prêt quand l\'extérieur est ferme et sec mais que l\'intérieur reste légèrement rosé et moelleux.',
      'Conserver dans un sac en papier ou un récipient ouvert (jamais hermétique) à température ambiante jusqu\'à 1 semaine, ou 1 mois au réfrigérateur. Trancher finement pour servir.',
    ],
    chefTip: 'La coriandre grossièrement moulue (pas en poudre fine) est la signature du biltong authentique — elle crée une croûte texturée distincte. La clé est une circulation d\'air constante : un ventilateur de cuisine suffit. L\'intérieur légèrement rosé n\'est pas un manque de cuisson mais la texture recherchée.',
    childNote: null,
  },
