  {
    id: 'nd-009', cuisine: 'nordique', name: 'Æbleskiver Danois',
    type: 'petit-déjeuner', difficulty: 'Moyen', prepTime: '15 min', cookTime: '20 min',
    servings: 4, kcalPerPerson: 340, proteinPerPerson: 10, carbsPerPerson: 48,
    diets: ['végétarien'], imageQuery: 'aebleskiver danish pancake balls powdered sugar jam',
    ingredients: [
      { quantity: '250', unit: 'g',   name: 'farine de blé' },
      { quantity: '3',   unit: '',    name: 'œufs (blancs et jaunes séparés)' },
      { quantity: '30',  unit: 'cl',  name: 'lait entier' },
      { quantity: '1',   unit: 'c.c', name: 'levure chimique' },
      { quantity: '1',   unit: 'c.s', name: 'sucre en poudre' },
      { quantity: '1',   unit: 'pincée', name: 'sel' },
      { quantity: '50',  unit: 'g',   name: 'beurre fondu' },
      { quantity: '1',   unit: 'c.c', name: 'extrait de vanille' },
    ],
    steps: [
      'Séparer les blancs des jaunes d\'œufs. Mélanger les jaunes avec le lait, le beurre fondu, la vanille et le sucre. Incorporer la farine, la levure et le sel pour former une pâte lisse.',
      'Monter les blancs en neige ferme avec une pincée de sel. Incorporer délicatement les blancs montés à la pâte en trois fois, en soulevant la masse pour conserver le maximum d\'air.',
      'Chauffer un moule à æbleskiver (ou une poêle à blinis) et beurrer chaque cavité. Remplir les cavités aux 2/3 de pâte.',
      'Lorsque la pâte commence à prendre sur les bords (après environ 2 minutes), piquer le fond avec un cure-dent en bois et faire pivoter chaque boule d\'un quart de tour pour former une sphère.',
      'Continuer à faire pivoter les boules toutes les 30 secondes jusqu\'à ce qu\'elles soient parfaitement rondes et dorées de toutes parts. Servir saupoudrés de sucre glace avec de la confiture de fraises ou de framboises.',
    ],
    chefTip: 'Le secret des æbleskiver parfaitement ronds réside dans la technique de rotation : il faut pivoter la boule par petits quarts de tour successifs avec un cure-dent, jamais d\'un coup. Les blancs en neige bien fermes sont indispensables pour la légèreté caractéristique.',
    childNote: 'Les enfants adorent les æbleskiver — les servir avec différentes confitures pour qu\'ils puissent choisir leur garniture.',
  },
  {
    id: 'nd-010', cuisine: 'nordique', name: 'Fårikål — Ragoût d\'Agneau Norvégien',
    type: 'dîner', difficulty: 'Facile', prepTime: '15 min', cookTime: '120 min',
    servings: 4, kcalPerPerson: 510, proteinPerPerson: 44, carbsPerPerson: 18,
    diets: ['sans-gluten'], imageQuery: 'farikal norwegian lamb cabbage stew winter dish',
    ingredients: [
      { quantity: '1',   unit: 'kg',  name: 'épaule d\'agneau coupée en morceaux avec os' },
      { quantity: '1',   unit: 'kg',  name: 'chou blanc coupé en quartiers' },
      { quantity: '2',   unit: 'c.s', name: 'grains de poivre noir entiers' },
      { quantity: '1',   unit: 'c.c', name: 'sel' },
      { quantity: '50',  unit: 'cl',  name: 'eau' },
      { quantity: '2',   unit: 'c.s', name: 'farine de blé (optionnel, pour lier)' },
    ],
    steps: [
      'Dans une grande cocotte à fond épais, alterner les couches : une couche de morceaux d\'agneau, puis une couche de quartiers de chou. Répéter l\'opération en terminant par le chou.',
      'Parsemer les grains de poivre entre les couches et saler. Verser l\'eau froide sur le tout.',
      'Porter à ébullition à couvert, puis réduire immédiatement le feu au minimum. Laisser mijoter très doucement pendant 1h30 à 2 heures sans mélanger.',
      'Le plat est prêt quand l\'agneau se détache facilement de l\'os et que le chou est fondant. Le bouillon doit être riche et gélatineux.',
      'Pour une sauce plus liée, prélever du bouillon, le mélanger avec la farine et reverser dans la cocotte. Servir directement dans la cocotte avec des pommes de terre bouillies.',
    ],
    chefTip: 'Le fårikål est un plat de patience : ne jamais mélanger durant la cuisson, laisser les couches se fondre naturellement. C\'est le plat national norvégien pour une bonne raison — sa simplicité extrême révèle la qualité de l\'agneau. Choisir des morceaux avec os pour un bouillon plus riche.',
    childNote: 'Plat naturellement doux et sans épices agressives — les enfants apprécient l\'agneau fondant et le chou confit servis avec des pommes de terre.',
  },
  {
    id: 'nd-011', cuisine: 'nordique', name: 'Janssons Frestelse — Gratin d\'Anchois Suédois',
    type: 'dîner', difficulty: 'Facile', prepTime: '20 min', cookTime: '50 min',
    servings: 4, kcalPerPerson: 420, proteinPerPerson: 14, carbsPerPerson: 42,
    diets: [], imageQuery: 'janssons frestelse swedish anchovy potato gratin cream',
    ingredients: [
      { quantity: '800', unit: 'g',   name: 'pommes de terre à chair ferme' },
      { quantity: '2',   unit: '',    name: 'oignons émincés en lamelles fines' },
      { quantity: '100', unit: 'g',   name: 'anchois suédois (sprats) ou anchois classiques' },
      { quantity: '30',  unit: 'cl',  name: 'crème fraîche liquide entière' },
      { quantity: '10',  unit: 'cl',  name: 'lait entier' },
      { quantity: '30',  unit: 'g',   name: 'chapelure' },
      { quantity: '30',  unit: 'g',   name: 'beurre en noisettes' },
    ],
    steps: [
      'Préchauffer le four à 200 °C. Peler et couper les pommes de terre en bâtonnets fins (comme des frites épaisses). Beurrer un plat à gratin.',
      'Dans une poêle, faire fondre une noix de beurre et faire revenir les oignons à feu doux jusqu\'à transparence sans coloration, environ 8 minutes.',
      'Alterner dans le plat beurré : couche de pommes de terre, couche d\'oignons fondus, filets d\'anchois. Répéter et terminer par une couche de pommes de terre.',
      'Mélanger la crème et le lait, verser sur le gratin. Parsemer de chapelure et disposer des noisettes de beurre en surface.',
      'Cuire au four 45-50 minutes jusqu\'à ce que les pommes de terre soient tendres et la surface bien dorée. Laisser reposer 5 minutes avant de servir.',
    ],
    chefTip: 'Le secret du Janssons Frestelse réside dans la douceur des anchois suédois (sprats en saumure) qui fondent dans la crème et disparaissent — le plat n\'a pas de goût de poisson prononcé mais une saveur umami profonde et salée. Couper les pommes de terre en bâtonnets réguliers garantit une cuisson homogène.',
    childNote: null,
  },
  {
    id: 'nd-012', cuisine: 'nordique', name: 'Finnish Salmon Soup — Lohikeitto',
    type: 'déjeuner', difficulty: 'Facile', prepTime: '15 min', cookTime: '25 min',
    servings: 4, kcalPerPerson: 390, proteinPerPerson: 32, carbsPerPerson: 28,
    diets: ['sans-gluten'], imageQuery: 'lohikeitto finnish salmon soup cream dill potato',
    ingredients: [
      { quantity: '500', unit: 'g',   name: 'filet de saumon sans peau coupé en cubes' },
      { quantity: '400', unit: 'g',   name: 'pommes de terre coupées en dés' },
      { quantity: '1',   unit: '',    name: 'poireau émincé en rondelles' },
      { quantity: '20',  unit: 'cl',  name: 'crème fraîche liquide' },
      { quantity: '80',  unit: 'cl',  name: 'fumet de poisson ou bouillon légumes' },
      { quantity: '1',   unit: '',    name: 'bouquet d\'aneth frais haché' },
      { quantity: '30',  unit: 'g',   name: 'beurre' },
      { quantity: '1',   unit: 'pincée', name: 'poivre blanc moulu' },
    ],
    steps: [
      'Dans une grande casserole, faire fondre le beurre à feu moyen. Faire revenir le poireau pendant 5 minutes sans coloration jusqu\'à ramollissement.',
      'Ajouter les dés de pommes de terre et le bouillon. Porter à ébullition, puis laisser cuire 12 minutes jusqu\'à ce que les pommes de terre soient presque tendres.',
      'Verser la crème fraîche, saler légèrement et poivrer. Laisser chauffer doucement sans faire bouillir.',
      'Ajouter les cubes de saumon. Couvrir et laisser pocher à feu très doux pendant 5 minutes — le saumon doit être juste cuit, encore légèrement nacré au centre.',
      'Retirer du feu, ajouter l\'aneth frais haché en grande quantité. Servir immédiatement dans des bols chauds avec du pain de seigle.',
    ],
    chefTip: 'Le saumon ne doit jamais bouillir dans la soupe : une ébullition trop vive le rend caoutchouteux et désagrège sa texture. Le pocher à couvert hors feu ou à frémissement doux préserve sa tendreté soyeuse. L\'aneth doit être ajouté hors du feu pour conserver ses arômes volatils.',
    childNote: 'Soupe très douce appréciée des enfants — servir avec du pain grillé et du beurre pour un repas complet et réconfortant.',
  },
  {
    id: 'nd-013', cuisine: 'nordique', name: 'Pyttipanna Suédois',
    type: 'déjeuner', difficulty: 'Facile', prepTime: '15 min', cookTime: '25 min',
    servings: 4, kcalPerPerson: 450, proteinPerPerson: 24, carbsPerPerson: 38,
    diets: [], imageQuery: 'pyttipanna swedish hash potatoes meat egg fried',
    ingredients: [
      { quantity: '500', unit: 'g',   name: 'pommes de terre cuites coupées en petits dés' },
      { quantity: '300', unit: 'g',   name: 'restes de viande cuite (bœuf, porc ou saucisse) en dés' },
      { quantity: '2',   unit: '',    name: 'oignons moyens coupés en dés' },
      { quantity: '4',   unit: '',    name: 'œufs (1 par personne, pour servir)' },
      { quantity: '3',   unit: 'c.s', name: 'beurre' },
      { quantity: '1',   unit: 'c.s', name: 'sauce soja' },
      { quantity: '1',   unit: 'c.c', name: 'poivre noir moulu' },
      { quantity: '2',   unit: 'c.s', name: 'persil frais haché' },
    ],
    steps: [
      'Dans une grande poêle à fond épais, faire fondre 2 c.s de beurre à feu vif. Faire dorer les dés de pommes de terre en une seule couche sans remuer pendant 3-4 minutes pour former une croûte. Retourner et dorer l\'autre face.',
      'Ajouter les oignons dans la poêle, réduire à feu moyen et cuire encore 5 minutes en remuant jusqu\'à ce que les oignons soient translucides.',
      'Incorporer les dés de viande, la sauce soja et le poivre. Faire sauter à feu vif 4-5 minutes jusqu\'à ce que tout soit bien doré et croustillant.',
      'Dans une poêle séparée, faire cuire les œufs au plat dans le beurre restant. Le jaune doit rester coulant.',
      'Dresser le pyttipanna dans des assiettes chaudes, poser un œuf au plat sur chaque portion. Parsemer de persil frais. Servir avec des betteraves marinées et de la moutarde de Dijon.',
    ],
    chefTip: 'Le pyttipanna (littéralement "petits morceaux dans la poêle") est le plat anti-gaspi suédois par excellence. La clé est de ne jamais remuer constamment : laisser les dés de pommes de terre former une croûte dorée avant de les retourner. La sauce soja apporte un umami inattendu très efficace.',
    childNote: 'Excellent plat pour utiliser les restes — les enfants apprécient les pommes de terre dorées et l\'œuf au plat. Adapter les garnitures selon les goûts.',
  },
  {
    id: 'nd-014', cuisine: 'nordique', name: 'Rugbrød — Pain de Seigle Maison',
    type: 'petit-déjeuner', difficulty: 'Difficile', prepTime: '30 min', cookTime: '90 min',
    servings: 12, kcalPerPerson: 180, proteinPerPerson: 6, carbsPerPerson: 32,
    diets: ['végétarien'], imageQuery: 'rugbrod danish rye bread sourdough dark dense loaf',
    ingredients: [
      { quantity: '400', unit: 'g',   name: 'farine de seigle intégrale' },
      { quantity: '100', unit: 'g',   name: 'farine de blé complète' },
      { quantity: '150', unit: 'g',   name: 'graines mélangées (lin, tournesol, courge)' },
      { quantity: '50',  unit: 'g',   name: 'céréales soufflées ou son d\'avoine' },
      { quantity: '10',  unit: 'g',   name: 'levure sèche instantanée' },
      { quantity: '1',   unit: 'c.c', name: 'sel fin' },
      { quantity: '1',   unit: 'c.s', name: 'mélasse ou sirop de malt' },
      { quantity: '40',  unit: 'cl',  name: 'eau tiède' },
    ],
    steps: [
      'Mélanger les deux farines, les graines, le son, la levure et le sel dans un grand bol. Creuser un puits, ajouter la mélasse et l\'eau tiède. Mélanger vigoureusement à la cuillère en bois — la pâte sera collante et dense, c\'est normal.',
      'Huiler généreusement un moule à cake de 25 cm. Verser la pâte, lisser le dessus avec une spatule humide. Couvrir d\'un film et laisser lever dans un endroit chaud pendant 1 heure.',
      'Préchauffer le four à 180 °C. Scarifier légèrement la surface du pain avec un couteau humide.',
      'Cuire 80-90 minutes. Le pain est cuit quand il sonne creux en tapotant le dessous. Si la surface dore trop vite, couvrir de papier aluminium.',
      'Indispensable : laisser refroidir complètement sur une grille — minimum 4 heures, idéalement une nuit — avant de trancher. Le rugbrød se tranche en fines lamelles et se conserve 1 semaine enveloppé dans du papier.',
    ],
    chefTip: 'Le rugbrød doit impérativement refroidir complètement avant d\'être tranché : coupé chaud, il s\'effrite et la texture reste gommeuse. Le lendemain, il se coupe en tranches nettes et sa saveur s\'est complexifiée. La mélasse apporte la couleur brune sombre et une légère amertume caractéristique.',
    childNote: null,
  },
  {
    id: 'nd-015', cuisine: 'nordique', name: 'Lefse Norvégien',
    type: 'collation', difficulty: 'Moyen', prepTime: '30 min', cookTime: '20 min',
    servings: 6, kcalPerPerson: 220, proteinPerPerson: 4, carbsPerPerson: 38,
    diets: ['végétarien'], imageQuery: 'norwegian lefse potato flatbread butter cinnamon',
    ingredients: [
      { quantity: '600', unit: 'g',   name: 'pommes de terre farineuses cuites et écrasées' },
      { quantity: '150', unit: 'g',   name: 'farine de blé (+ pour le plan de travail)' },
      { quantity: '3',   unit: 'c.s', name: 'beurre fondu' },
      { quantity: '10',  unit: 'cl',  name: 'crème fraîche épaisse' },
      { quantity: '1',   unit: 'pincée', name: 'sel' },
      { quantity: '50',  unit: 'g',   name: 'beurre mou (pour servir)' },
      { quantity: '2',   unit: 'c.s', name: 'sucre et cannelle mélangés (pour servir)' },
    ],
    steps: [
      'Mélanger la purée de pommes de terre (froide) avec le beurre fondu, la crème fraîche et le sel. Incorporer la farine progressivement pour obtenir une pâte souple et non collante. Ne pas trop travailler la pâte.',
      'Diviser la pâte en 12 boules égales. Réfrigérer 15 minutes — la pâte froide est plus facile à étaler.',
      'Sur un plan de travail bien fariné, étaler chaque boule en un disque très fin (2 mm) avec un rouleau à pâtisserie. Plus c\'est fin, meilleur c\'est.',
      'Cuire chaque lefse sur une plaque ou une grande poêle sèche très chaude, 1 à 2 minutes de chaque côté. Des taches brunes doivent apparaître. Empiler les lefse cuits sous un linge propre pour les garder souples.',
      'Servir les lefse chauds tartinés de beurre mou et saupoudrés du mélange sucre-cannelle, puis enroulés. Ils peuvent aussi être servis avec du saumon fumé ou du fromage.',
    ],
    chefTip: 'La purée de pommes de terre doit être parfaitement froide et sèche avant d\'incorporer la farine : une purée chaude ou humide rend la pâte collante et difficile à étaler. Éviter les pommes de terre riches en eau — choisir des variétés farineuses comme la Bintje.',
    childNote: 'Les lefse au beurre et à la cannelle sont comme des crêpes nordiques — les enfants adorent les enrouler eux-mêmes avec leurs garnitures préférées.',
  },
  {
    id: 'nd-016', cuisine: 'nordique', name: 'Ris à l\'Amande Danois',
    type: 'dessert', difficulty: 'Facile', prepTime: '15 min', cookTime: '30 min',
    servings: 6, kcalPerPerson: 380, proteinPerPerson: 7, carbsPerPerson: 42,
    diets: ['végétarien'], imageQuery: 'ris alamande danish rice pudding almonds cherry sauce',
    ingredients: [
      { quantity: '300', unit: 'g',   name: 'riz à dessert (riz rond)' },
      { quantity: '80',  unit: 'cl',  name: 'lait entier' },
      { quantity: '100', unit: 'g',   name: 'amandes entières émondées' },
      { quantity: '30',  unit: 'cl',  name: 'crème fraîche entière très froide' },
      { quantity: '3',   unit: 'c.s', name: 'sucre en poudre' },
      { quantity: '1',   unit: 'c.c', name: 'extrait de vanille' },
      { quantity: '200', unit: 'g',   name: 'cerises griottes en conserve avec leur jus' },
    ],
    steps: [
      'Cuire le riz dans le lait avec la vanille à feu très doux, en remuant régulièrement, pendant 25-30 minutes jusqu\'à ce qu\'il soit très tendre et crémeux. Laisser refroidir complètement.',
      'Pendant que le riz refroidit, effiler grossièrement les amandes — garder une amande entière que vous cacherez dans le plat (tradition danoise de Noël : celui qui la trouve reçoit un cadeau).',
      'Monter la crème fraîche bien froide en chantilly avec le sucre. Incorporer délicatement la chantilly au riz froid en soulevant la masse pour ne pas faire retomber la crème.',
      'Incorporer les amandes effilées. Réserver au frais au minimum 1 heure avant de servir.',
      'Préparer la sauce en chauffant les cerises avec leur jus 5 minutes pour former un coulis. Servir le ris à l\'amande en coupelles avec la sauce aux cerises chaude versée au dernier moment.',
    ],
    chefTip: 'Le riz doit être complètement froid avant d\'incorporer la chantilly — un riz tiède ferait fondre la crème et le résultat serait liquide. La chantilly doit être incorporée en trois fois avec un mouvement enveloppant pour conserver le maximum d\'air et obtenir la légèreté caractéristique du dessert.',
    childNote: 'Tradition adorée des enfants danois — cacher l\'amande entière dans le plat crée un jeu de Noël amusant. Servir avec des biscuits en forme d\'étoile.',
  },
  {
    id: 'nd-017', cuisine: 'nordique', name: 'Biff à la Lindström',
    type: 'déjeuner', difficulty: 'Facile', prepTime: '20 min', cookTime: '15 min',
    servings: 4, kcalPerPerson: 460, proteinPerPerson: 32, carbsPerPerson: 22,
    diets: [], imageQuery: 'biff lindstrom swedish beef patties beetroot capers fried',
    ingredients: [
      { quantity: '600', unit: 'g',   name: 'bœuf haché (15% de matière grasse)' },
      { quantity: '150', unit: 'g',   name: 'betteraves marinées finement hachées' },
      { quantity: '2',   unit: 'c.s', name: 'câpres égouttées hachées' },
      { quantity: '1',   unit: '',    name: 'oignon moyen finement haché' },
      { quantity: '2',   unit: '',    name: 'jaunes d\'œufs' },
      { quantity: '5',   unit: 'cl',  name: 'crème fraîche' },
      { quantity: '2',   unit: 'c.s', name: 'beurre' },
      { quantity: '1',   unit: 'c.c', name: 'sel et poivre noir' },
    ],
    steps: [
      'Dans un grand bol, mélanger le bœuf haché, les betteraves hachées, les câpres, l\'oignon, les jaunes d\'œufs et la crème fraîche. Saler et poivrer généreusement.',
      'Travailler la farce à la main jusqu\'à obtenir un mélange homogène. La betterave va teinter la viande d\'un rose-rouge caractéristique.',
      'Former 8 galettes rondes d\'environ 2 cm d\'épaisseur. Réfrigérer 10 minutes pour que les galettes se raffermissent.',
      'Faire chauffer le beurre dans une grande poêle à feu moyen-vif. Cuire les galettes 3-4 minutes de chaque côté jusqu\'à croûte bien dorée. L\'intérieur peut rester légèrement rosé.',
      'Servir immédiatement avec des pommes de terre en purée ou des frites, de la crème aigre et une salade de betteraves. Un œuf au plat posé sur chaque galette est traditionnel.',
    ],
    chefTip: 'La betterave apporte humidité et sucre à la farce — elle peut rendre les galettes fragiles à la manipulation. Réfrigérer les galettes avant cuisson les raffermit et empêche qu\'elles se désagrègent. Ne pas trop cuire : l\'intérieur rosé est voulu et différencie ce plat d\'un simple hamburger.',
    childNote: 'La couleur rose-rouge peut surprendre les enfants — expliquer que c\'est la betterave et que c\'est naturel. Le goût est doux et légèrement sucré, généralement apprécié.',
  },
  {
    id: 'nd-018', cuisine: 'nordique', name: 'Sill — Hareng Mariné à la Moutarde',
    type: 'déjeuner', difficulty: 'Facile', prepTime: '15 min', cookTime: '0 min',
    servings: 4, kcalPerPerson: 260, proteinPerPerson: 18, carbsPerPerson: 8,
    diets: ['sans-gluten'], imageQuery: 'swedish sill pickled herring mustard sauce dill',
    ingredients: [
      { quantity: '400', unit: 'g',   name: 'filets de hareng en saumure (rincés)' },
      { quantity: '3',   unit: 'c.s', name: 'moutarde suédoise douce (ou moutarde à l\'ancienne)' },
      { quantity: '2',   unit: 'c.s', name: 'vinaigre de vin blanc' },
      { quantity: '2',   unit: 'c.s', name: 'sucre en poudre' },
      { quantity: '5',   unit: 'cl',  name: 'huile végétale neutre' },
      { quantity: '1',   unit: '',    name: 'bouquet d\'aneth frais ciselé' },
      { quantity: '1',   unit: '',    name: 'échalote finement émincée' },
    ],
    steps: [
      'Rincer les filets de hareng sous l\'eau froide pour enlever l\'excès de sel. Les sécher avec du papier absorbant et les couper en morceaux de 4 cm.',
      'Dans un bol, fouetter la moutarde, le vinaigre et le sucre jusqu\'à dissolution du sucre. Verser l\'huile en filet en continuant de fouetter pour émulsionner la marinade.',
      'Ajouter l\'aneth ciselé et l\'échalote à la marinade. Goûter et ajuster l\'équilibre sucré-acide selon les préférences.',
      'Ajouter les morceaux de hareng et mélanger délicatement pour bien les enrober. Couvrir et laisser mariner au réfrigérateur minimum 2 heures (idéalement une nuit).',
      'Servir frais sur du pain de seigle grillé avec des pommes de terre nouvelles bouillies, de la crème aigre et de l\'aneth supplémentaire. Accompagner d\'un verre d\'aquavit selon la tradition.',
    ],
    chefTip: 'L\'équilibre moutarde-sucre-vinaigre est la clé du sill : la moutarde doit être douce (jamais la moutarde forte française qui domine tout). Laisser mariner une nuit entière est crucial : les saveurs se fondent et le hareng perd son goût iodé prononcé pour prendre un profil plus doux et complexe.',
    childNote: null,
  },
  {
    id: 'nd-019', cuisine: 'nordique', name: 'Toast Skagen',
    type: 'collation', difficulty: 'Facile', prepTime: '20 min', cookTime: '5 min',
    servings: 4, kcalPerPerson: 310, proteinPerPerson: 20, carbsPerPerson: 18,
    diets: [], imageQuery: 'toast skagen swedish shrimp crayfish mayonnaise dill blini',
    ingredients: [
      { quantity: '300', unit: 'g',   name: 'crevettes roses cuites décortiquées' },
      { quantity: '4',   unit: 'c.s', name: 'mayonnaise de qualité' },
      { quantity: '2',   unit: 'c.s', name: 'crème fraîche épaisse' },
      { quantity: '1',   unit: '',    name: 'bouquet d\'aneth frais ciselé' },
      { quantity: '1',   unit: '',    name: 'citron (jus + zeste)' },
      { quantity: '4',   unit: '',    name: 'tranches de pain brioché ou de brioche' },
      { quantity: '30',  unit: 'g',   name: 'beurre' },
      { quantity: '50',  unit: 'g',   name: 'œufs de lump (optionnel, pour garnir)' },
    ],
    steps: [
      'Hacher grossièrement la moitié des crevettes au couteau, garder le reste entier pour la texture et la présentation.',
      'Dans un bol, mélanger la mayonnaise, la crème fraîche, le jus de citron, le zeste et l\'aneth ciselé. Assaisonner de sel, poivre blanc et une pincée de sucre.',
      'Incorporer toutes les crevettes (hachées et entières) à la sauce. Goûter et ajuster. Réfrigérer 15 minutes.',
      'Tartiner les tranches de pain de beurre et les griller dans une poêle ou au grille-pain jusqu\'à légère dorure.',
      'Déposer généreusement la garniture de crevettes sur les toasts chauds. Garnir d\'une branche d\'aneth, de quelques œufs de lump et d\'un quartier de citron. Servir immédiatement.',
    ],
    chefTip: 'La qualité des crevettes est primordiale pour le Toast Skagen : utiliser des crevettes fraîches ou surgelées de qualité, jamais des crevettes en conserve au vinaigre. Hacher une partie des crevettes permet à la garniture de tenir sur le toast tout en gardant des morceaux identifiables.',
    childNote: 'Omettre les œufs de lump et la crème fraîche pour les plus jeunes — des crevettes simples avec une mayonnaise légère sont suffisantes et délicieuses.',
  },
  {
    id: 'nd-020', cuisine: 'nordique', name: 'Raggmunk — Galettes de Pommes de Terre Suédoises',
    type: 'déjeuner', difficulty: 'Facile', prepTime: '15 min', cookTime: '20 min',
    servings: 4, kcalPerPerson: 350, proteinPerPerson: 10, carbsPerPerson: 42,
    diets: ['végétarien'], imageQuery: 'raggmunk swedish potato pancakes lingonberry bacon',
    ingredients: [
      { quantity: '600', unit: 'g',   name: 'pommes de terre crues râpées finement' },
      { quantity: '2',   unit: '',    name: 'œufs battus' },
      { quantity: '10',  unit: 'cl',  name: 'lait entier' },
      { quantity: '4',   unit: 'c.s', name: 'farine de blé' },
      { quantity: '1',   unit: 'c.c', name: 'sel' },
      { quantity: '3',   unit: 'c.s', name: 'beurre clarifié ou huile végétale' },
      { quantity: '4',   unit: 'c.s', name: 'confiture de lingonberries (ou airelles)' },
    ],
    steps: [
      'Râper finement les pommes de terre avec une râpe à gros trous. Déposer dans un torchon propre et tordre énergiquement pour extraire le maximum d\'eau — c\'est l\'étape la plus importante.',
      'Dans un bol, mélanger les pommes de terre râpées pressées avec les œufs battus, le lait, la farine et le sel. La pâte sera épaisse et collante.',
      'Chauffer le beurre clarifié dans une grande poêle à feu moyen-vif. Déposer des cuillerées de pâte et aplatir délicatement en galettes de 10 cm de diamètre.',
      'Cuire 3-4 minutes sans toucher jusqu\'à ce que les bords soient bien dorés et croustillants. Retourner délicatement et cuire encore 3 minutes.',
      'Servir immédiatement avec la confiture de lingonberries et du bacon croustillant ou de la crème aigre. Les raggmunk ramollissent vite — les servir à la sortie de la poêle.',
    ],
    chefTip: 'Extraire le maximum d\'eau des pommes de terre râpées est absolument crucial : des pommes de terre humides donnent des galettes molles et qui ne colorent pas. Tordre le torchon jusqu\'à ce qu\'il n\'en sorte plus une goutte. Le beurre clarifié supporte mieux la chaleur que le beurre entier pour une dorure optimale.',
    childNote: 'Les galettes de pommes de terre avec de la confiture d\'airelles sont adorées des enfants — un classique suédois du goûter ou du déjeuner.',
  },
  {
    id: 'nd-021', cuisine: 'nordique', name: 'Leverpostej — Pâté de Foie Danois',
    type: 'collation', difficulty: 'Moyen', prepTime: '20 min', cookTime: '50 min',
    servings: 8, kcalPerPerson: 290, proteinPerPerson: 14, carbsPerPerson: 8,
    diets: [], imageQuery: 'leverpostej danish liver pate rye bread mushrooms bacon',
    ingredients: [
      { quantity: '400', unit: 'g',   name: 'foie de porc ou de veau' },
      { quantity: '150', unit: 'g',   name: 'lard gras coupé en dés' },
      { quantity: '1',   unit: '',    name: 'oignon moyen grossièrement haché' },
      { quantity: '2',   unit: '',    name: 'œufs' },
      { quantity: '20',  unit: 'cl',  name: 'crème fraîche liquide' },
      { quantity: '2',   unit: 'c.s', name: 'farine de blé' },
      { quantity: '1',   unit: 'c.c', name: 'marjolaine séchée' },
      { quantity: '1',   unit: 'c.c', name: 'sel et poivre de muscade râpé' },
    ],
    steps: [
      'Préchauffer le four à 175 °C. Couper le foie en morceaux en retirant les nerfs et les membranes. Faire tremper 30 minutes dans de l\'eau froide légèrement salée, puis égoutter.',
      'Mixer le foie, le lard et l\'oignon dans un blender jusqu\'à obtenir une pâte lisse. Ajouter les œufs, la crème, la farine, la marjolaine, le sel et le poivre. Mixer jusqu\'à consistance homogène.',
      'Passer la farce au tamis fin pour obtenir une texture parfaitement lisse — cette étape est optionnelle mais donne un résultat professionnel.',
      'Verser dans une terrine beurrée, couvrir de papier aluminium. Cuire au bain-marie au four pendant 50 minutes. Le pâté est cuit quand un couteau planté au centre ressort propre.',
      'Laisser refroidir complètement avant de réfrigérer minimum 4 heures. Servir sur du pain de seigle avec des cornichons, des champignons sautés et du bacon grillé.',
    ],
    chefTip: 'Le trempage du foie dans l\'eau froide est essentiel pour éliminer le sang et adoucir le goût fort du foie. La cuisson au bain-marie garantit une texture moelleuse et uniforme : sans bain-marie, les bords cuisent trop vite et craquèlent. Le leverpostej est bien meilleur le lendemain.',
    childNote: null,
  },
  {
    id: 'nd-022', cuisine: 'nordique', name: 'Lutefisk — Morue à la Lessive de Soude',
    type: 'dîner', difficulty: 'Difficile', prepTime: '10 min', cookTime: '15 min',
    servings: 4, kcalPerPerson: 190, proteinPerPerson: 34, carbsPerPerson: 4,
    diets: ['sans-gluten'], imageQuery: 'lutefisk norwegian cod lye fish bacon peas traditional',
    ingredients: [
      { quantity: '800', unit: 'g',   name: 'lutefisk (morue préparée à la lessive, prête à cuire)' },
      { quantity: '150', unit: 'g',   name: 'lard fumé ou bacon en lardons' },
      { quantity: '200', unit: 'g',   name: 'petits pois surgelés' },
      { quantity: '4',   unit: 'c.s', name: 'moutarde forte' },
      { quantity: '50',  unit: 'g',   name: 'beurre' },
      { quantity: '1',   unit: 'c.c', name: 'poivre blanc moulu' },
      { quantity: '1',   unit: 'c.c', name: 'sel' },
    ],
    steps: [
      'Préchauffer le four à 200 °C. Le lutefisk acheté prêt à cuire ne nécessite pas de préparation supplémentaire. Le rincer délicatement à l\'eau froide et l\'éponger avec du papier absorbant.',
      'Saler légèrement le lutefisk et le placer dans un plat allant au four. Couvrir hermétiquement de papier aluminium — le poisson doit cuire dans sa propre eau.',
      'Cuire au four 12-15 minutes. Le lutefisk est prêt quand il commence à s\'opacifier et à se défaire légèrement. Ne pas trop cuire, sinon la texture gélatineuse devient aqueuse.',
      'Pendant ce temps, faire griller les lardons à sec dans une poêle jusqu\'à croustillants. Faire chauffer les petits pois dans le beurre fondu.',
      'Dresser le lutefisk délicatement (il est fragile), napper des lardons croustillants et des petits pois. Servir avec de la moutarde forte à côté, des pommes de terre à l\'eau et du pain de seigle.',
    ],
    chefTip: 'Le lutefisk est un plat de tradition plus que de gastronomie — sa texture gélatineuse unique est un marqueur culturel nordique. La clé est de ne jamais le surcuire : il doit à peine s\'opacifier. Les lardons croustillants et la moutarde forte sont indispensables pour équilibrer sa texture neutre.',
    childNote: null,
  },
  {
    id: 'nd-023', cuisine: 'nordique', name: 'Cloudberry Mousse — Mousse aux Baies de Nuage',
    type: 'dessert', difficulty: 'Facile', prepTime: '20 min', cookTime: '0 min',
    servings: 4, kcalPerPerson: 280, proteinPerPerson: 4, carbsPerPerson: 26,
    diets: ['végétarien'], imageQuery: 'cloudberry mousse nordic arctic berry cream dessert',
    ingredients: [
      { quantity: '250', unit: 'g',   name: 'baies de nuage (cloudberries) fraîches ou surgelées' },
      { quantity: '30',  unit: 'cl',  name: 'crème fraîche entière très froide' },
      { quantity: '3',   unit: 'c.s', name: 'sucre glace' },
      { quantity: '1',   unit: 'c.c', name: 'extrait de vanille' },
      { quantity: '2',   unit: 'c.s', name: 'sucre en poudre' },
      { quantity: '1',   unit: 'c.s', name: 'jus de citron' },
    ],
    steps: [
      'Si les baies sont surgelées, les décongeler à température ambiante et égoutter l\'excès de jus. Réserver 8 belles baies entières pour la décoration.',
      'Écraser grossièrement les baies restantes avec le sucre en poudre et le jus de citron à la fourchette — conserver des morceaux pour la texture, ne pas mixer en purée lisse.',
      'Monter la crème fraîche très froide en chantilly ferme avec le sucre glace et la vanille. Arrêter quand la crème forme des pics fermes.',
      'Incorporer délicatement les baies écrasées à la chantilly en trois fois, avec un mouvement enveloppant. Ne pas trop mélanger — les filaments orange-dorés de baies dans la crème blanche sont visuellement magnifiques.',
      'Répartir dans des verrines. Décorer avec les baies entières réservées. Réfrigérer minimum 30 minutes avant de servir. Servir avec des petits gâteaux nordiques sablés.',
    ],
    chefTip: 'Les cloudberries (baies de nuage) sont rares et précieuses — leur saveur acidulée et florale est unique. Ne jamais les mixer : écraser à la fourchette préserve leur texture et leurs arômes fragiles. L\'aspect marbré orange-blanc est la signature visuelle de ce dessert : ne pas trop mélanger pour conserver cet effet.',
    childNote: 'Dessert très apprécié des enfants grâce à sa douceur et sa belle couleur — remplacer les cloudberries par des framboises ou des abricots si introuvables.',
  },
